# Site settings

title: Ilmastoveivi 2019
desc: Ilmastoveivillä kampeamme Suomen ilmastoasioiden kansainväliseen kärkeen. Kiekko on jo liikkeellä, ratkaisun paikka on nyt.
image: https://www.ilmastoveivi2019.fi/share.png
twitter: Ilmastoveivi19
facebook: ilmastoveivi2019
instagram: ilmastoveivi2019/
#slogan: Ollaan me ihmeitä ennenkin tehty
share-title: Ollaan me ihmeitä ennenkin tehty
share-text: Ilmastoveivillä kampeamme Suomen ilmastoasioiden kansainväliseen kärkeen. Kiekko on jo liikkeellä, ratkaisun paikka on nyt. http://ilmastoveivi2019.fi
share-url: https://ilmastoveivi2019.fi
ga: UA-129569534-1

index:
    fi: index.md
    se: se.md
    en: en.md

# Build settings
sass:
    sass_dir: _sass
    style: compressed
