# Site settings

title: Ilmastoveivi 2019
desc: Ilmastoveivillä kampeamme Suomen ilmastoasioiden kansainväliseen kärkeen. Kiekko on jo liikkeellä, ratkaisun paikka on nyt.
image: https://www.ilmastoveivi2019.fi/share.png
twitter: Ilmastoveivi19
twitter-share-text: Allekirjoitin &#37;23ilmastoveivi2019 -vetoomuksen. Ilmastoveivillä kampeamme Suomen ilmastoasioiden kansainväliseen kärkeen. Kiekko on jo liikkeellä, ratkaisun paikka on nyt. http://ilmastoveivi2019.fi
facebook: ilmastoveivi2019
instagram: ilmastoveivi2019/
#slogan: Ollaan me ihmeitä ennenkin tehty
share-title: Ollaan me ihmeitä ennenkin tehty
share-text: Ilmastoveivillä kampeamme Suomen ilmastoasioiden kansainväliseen kärkeen. Kiekko on jo liikkeellä, ratkaisun paikka on nyt. http://ilmastoveivi2019.fi
share-url: https://ilmastoveivi2019.fi
typeform-url-fi: https://ilmastoveivi.typeform.com/to/WpWzgl
typeform-url-sv: https://ilmastoveivi.typeform.com/to/iqFagL
typeform-url-en: https://ilmastoveivi.typeform.com/to/xqKy2P
typeform-redirect-fi: https://ilmastoveivi2019.fi/kiitos.html
typeform-redirect-sv: https://ilmastoveivi2019.fi/tackar.html
typeform-redirect-en: https://ilmastoveivi2019.fi/thanks.html
ga: UA-129569534-1

index:
    fi: index.md
    se: se.md
    en: en.md

# Build settings
sass:
    sass_dir: _sass
    style: compressed
